### ISSUE TITLE
鹅妹子嘤

### ISSUE THREAD

**Issue by xuyisheng** [mthli/Mount#2]
厉害了我的亮，how to uninstall~

**Comment by mthli** [comment]
在应用的设置里，点击「预备卸载」，然后你就可以卸载这款 App 了。

**Comment by xuyisheng** [comment]
thx ，用代码卸了，API21的Device Owner权限真是太大了！

**Comment by 2017398956** [comment]
我来占个沙发，离医生近点╭(●｀∀´●)╯╰(●’◡’●)╮ (●’◡’●)ﾉ ヾ(*´▽‘*)ﾉ
