### ISSUE TITLE
用了2个手机, 没成功过...

### ISSUE THREAD

**Issue by csshuai** [mthli/Mount#4]
emui  我删除了所有账户后还是
java.lang.IllegalStateException: Not allowed to set the device owner because there are already some accounts on the device

miui
Error: Unknown admin: ComponentInfo{io.github.mthli.mount/io.github.mthli.mount.app.MountReceiver}

**Comment by mthli** [comment]
可能有系统隐藏的帐号，必须把帐号移除干净。
